### ISSUE TITLE
Git suggestion for push stopped working

### ISSUE THREAD

**Issue by skalinets** [mattparkes/PoShFuck#13]
I haven't been using poshfuck for a while (something got broken with python and installation did not work for me #10). However today I managed to install it and one of my favorite actions (99% of my usage) apparently stopped working. It is when you want to push a new git branch to remote, git don't want to do that asking for additional parameters (`--set-upstream` and so on). I usually answered `fuck` and it did all the magic, running `git push` with required parameters. But now this happens:

```
C:\Users\admin\work\my-repo [feature/my-feature]> git push
fatal: The current branch feature/my-feature has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin feature/my-feature

C:\Users\admin\work\my-repo [feature/my-feature]> fuck

Did you mean?
 git push
[Y] Yes  [N] No  [?] Help (default is "Y"):
fatal: The current branch feature/my-feature has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin feature/my-feature

C:\Users\admin\work\my-repo [feature/my-feature]>
```

So it basically re-runs the same command, instead of figuring out the correct one. 

My configuration:
* git version: 2.8.2.windows.1
* powershel versionl: 5.1.15063.608
* windows 10 home edition
* poshfuck version: f459170 (git hash)

**Comment by nialfrancis** [comment]
Reverted, please open a new issue if not due to the age of this
