### ISSUE TITLE
GIT Issues 2: Electric Boogaloo

### ISSUE THREAD

**Issue by Atulin** [mattparkes/PoShFuck#17]
![image](https://user-images.githubusercontent.com/11233299/48230857-b11abe00-e3ac-11e8-8dca-82bbde806f70.png)
![image](https://user-images.githubusercontent.com/11233299/48230888-c7c11500-e3ac-11e8-8a41-575be8479e6d.png)

**Comment by nialfrancis** [comment]
Should be fixed now, but next commit I will see if I can make it fix 2 wrong commands at once

**Comment by aejay-rs** [comment]
![Applause](https://media.giphy.com/media/143WAqb351Q1Vu/giphy.gif)
