### ISSUE TITLE
Install-TheFucker: Windows 10 PATH env

### ISSUE THREAD

**Issue by reideast** [mattparkes/PoShFuck#3]
On Windows 10, PowerShell 5 ($PSVersionTable.PSVersion = 5.0.10586.63),  my %PATH% variable has a trailing slash. I'm not sure if this is a strange artifact on my machine, but it causes
$pfk to be "C:\Users\User\AppData\Local\Temp\\poshfuck.zip", and the double "\\" slash prevents the install from working.

I created a pull request #2 that fixes the issue by using Join-Path, per your example.

Thanks for writing this implementation!

**Comment by mattparkes** [comment]
Thanks for the Pull Request. I've reviewed it and merged it in.

I hope you have fun with PoShFuck!
