### ISSUE TITLE
Better at guessing GIT?

### ISSUE THREAD

**Issue by Saturate** [mattparkes/PoShFuck#9]
It seems like it's just trying to run the same command again when I'm using git.

![image](https://user-images.githubusercontent.com/453018/27679165-1195e7f0-5cb8-11e7-87f5-9da5a376262f.png)

**Comment by nialfrancis** [comment]
Hi mate,

Interesting issue, there is a todo already to separate fixing commands and arguments, which i think is the cause of your problem - a good cmd and bad arg.

I'll have a look in the next few days, and ensure the module is updatable.

Nial

**Comment by Saturate** [comment]
Thanks, sorry for the lacking bug report - I'm a bit busy.

However here is some additional information:

- Windows 10
- git version 2.10.2.windows.1

PowerShell:

```
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      15063  296
```

**Comment by nialfrancis** [comment]
It now guesses git
